src/Entity/Documentation.php
<?php

namespace App\Entity;

use App\Repository\DocumentationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DocumentationRepository::class)
 */
class Documentation
{
    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->id;
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $document;

    /**
     * @ORM\OneToOne(targetEntity=Customers::class, inversedBy="documentation", cascade={"persist", "remove"})
     */
    private $customers_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDocument(): ?string
    {
        return $this->document;
    }

    public function setDocument(?string $document): self
    {
        $this->document = $document;

        return $this;
    }

    public function getCustomersId(): ?Customers
    {
        return $this->customers_id;
    }

    public function setCustomersId(?Customers $customers_id): self
    {
        $this->customers_id = $customers_id;

        return $this;
    }
}

src/Entity/UserSociety.php
<?php

namespace App\Entity;

use App\Repository\UserSocietyRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserSocietyRepository::class)
 */
class UserSociety
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Address;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ZipCode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $City;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist", "merge", "remove"})
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(?string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->ZipCode;
    }

    public function setZipCode(?int $ZipCode): self
    {
        $this->ZipCode = $ZipCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(?string $City): self
    {
        $this->City = $City;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}Gestion-Accueil{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="" />
    {{ encore_entry_link_tags('app') }}
    {% block stylesheets %}{% endblock %}
</head>
<body class="left-sidebar is-preload">
    <div id="page-wrapper">

    {% block header %}{% endblock %}
    {% block login %}{% endblock %}
    {% block body %}{% endblock %}
    {% block footer %}{% endblock %}
    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
    </div>
</body>
</html>

templates/customer.html.twig
{% if documentation.customersId != null%}
        <p>{{ documentation.customersId.name }}</p>
        <p>{{ documentation.customersId.address }}</p>
        <ul class="actions">
            {% if documentation.customersId.phone1 != null %}
                <li class="">0{{ documentation.customersId.phone1 }}</li>
            {% endif %}
            {% if documentation.customersId.phone2 != null %}
                <li class="">0{{ documentation.customersId.phone2 }}</li>
            {% endif %}
            {% if documentation.customersId.phone3 != null %}
                <li class="">0{{ documentation.customersId.phone3 }}</li>
            {% endif %}
        </ul>
{% else %}
        <p>{{ customerid.name }}</p>
        <p>{{ customerid.address }}</p>
        <ul class="actions">
                {% if customerid.phone1 != null %}
                        <li class="">0{{ customerid.phone1 }}</li>
                {% endif %}
                {% if customerid.phone2 != null %}
                        <li class="">0{{ customerid.phone2 }}</li>
                {% endif %}
                {% if customerid.phone3 != null %}
                        <li class="">0{{ customerid.phone3 }}</li>
                {% endif %}
        </ul>

{% endif %}

templates/index.html.twig
{% extends 'layout.html.twig' %}
{% block body %}
    <!-- Intro -->
    <section id="intro" class="container">
        <div class="row">
            <a href="{{ path('internal_documents_index') }}">
                <div class="col-4 col-12-medium">
                    <section class="first">
                        <i class="icon solid featured fa-cog"></i>
                        <header>
                            <h2>Keep Connection</h2>
                        </header>
                        <p>Documentation sur les pannes et le réseau keep</p>
                    </section>
                </div>
            </a>
            <a href="{{ path('customers_index') }}">
                <div class="col-4 col-12-medium">
                    <section class="middle">
                        <i class="icon solid featured alt fa-bolt"></i>
                        <header>
                            <h2>Clients</h2>
                        </header>
                        <p>Documentation sur le réseau de la liste clients</p>
                    </section>
                </div>
            </a>
            <a href="{{ path('prices_index') }}">
                <div class="col-4 col-12-medium">
                    <section class="last">
                        <i class="icon solid featured alt2 fa-star"></i>
                        <header>
                            <h2>Tarifs</h2>
                        </header>
                        <p>Grille tarifaire</p>
                    </section>
                </div>
            </a>
        </div>
    </section>

{% endblock %}

templates/layout.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    <!-- Header -->
<section id="header">
    <!-- Banner -->
    <section id="banner">
        <a href="{{ path('homepage') }}">
            <header>
                <h2>DOCUMENTATION DES RESEAUX CLIENTS</h2>
                <p>Documentation et partages des informations clientèle</p>
            </header>
        </a>
    </section>
{% endblock %}
{% block footer %}
    <!-- Footer -->
    <section id="footer">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <section>
                        <ul class="social">
                            <li><a class="icon brands fa-facebook-f" href="#"><span class="label">Facebook</span></a></li>
                            <li><a class="icon brands fa-twitter" href="#"><span class="label">Twitter</span></a></li>
                            <li><a class="icon brands fa-dribbble" href="#"><span class="label">Dribbble</span></a></li>
                            <li><a class="icon brands fa-tumblr" href="#"><span class="label">Tumblr</span></a></li>
                            <li><a class="icon brands fa-linkedin-in" href="#"><span class="label">LinkedIn</span></a></li>
                        </ul>
                    </section>
                </div>
                <div class="col-12">

                    <!-- Copyright -->
                    <div id="copyright">
                        <ul class="links">
                            <li>&copy; <a href="cybix-technology.com">Cybix-Technology.</a> All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

templates/list.html.twig
<input id="searchbar" onkeyup="search()" type="text" name="search" placeholder="rechercher" />
</br>
<ul class="divided" id="list">
    {% for customer in customers %}
        <li class="blocs"><a href="{{ path('documentation_try', {'id': customer.id}) }}">{{ customer.name }}</a></li>
    {% endfor %}
</ul>

<script type="javascript">
// JavaScript code
function search() {
        let input = document.getElementById('searchbar').value
        input=input.toLowerCase();
        let x = document.getElementsByClassName('blocs');

        for (i = 0; i < x.length; i++) {
                if (!x[i].innerHTML.toLowerCase().includes(input)) {
                        x[i].style.display="none";
                }
                else {
                        x[i].style.display="bloc";
                }
        }
}
</script>